server:
  port: 8081

spring:
  application:
    name: apigw-service

  main:
    web-application-type: reactive  # Enforce reactive stack (WebFlux)

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
      shutdown-timeout: 3000  # Redis connection timeout in milliseconds

  cloud:
    gateway:
      routes:
        - id: abac-auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - RequestRateLimiter=replenishRate=10, burstCapacity=20  # Rate limiting for /auth/**
            - CircuitBreaker=name=authServiceCircuitBreaker, fallbackUri=/fallback/auth-service  # Circuit breaker for auth service
        - id: resource-service
          uri: http://localhost:8083
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
            - RequestRateLimiter=replenishRate=10, burstCapacity=20  # Rate limiting for /resource/**
            - CircuitBreaker=name=resourceServiceCircuitBreaker, fallbackUri=/fallback/resource-service  # Circuit breaker for resource service

      # Global settings for the gateway HTTP client
      httpclient:
        connect-timeout: 3000  # Connection timeout for upstream services (in milliseconds)
        response-timeout: 5000  # Response timeout for upstream services (in milliseconds)

      # Default filters for all routes
      default-filters:
        - name: SecureHeaders  # Adds secure headers globally

      # Metrics enabled for monitoring
      metrics:
        enabled: true

# JWT Configuration - for validating tokens via JWKS
jwt:
  jwksUri: "http://localhost:8082/auth/.well-known/jwks.json"

# Resilience4J circuit breaker settings for auth-service and resource-service
resilience4j:
  circuitbreaker:
    instances:
      authServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000  # 10 seconds
        permittedNumberOfCallsInHalfOpenState: 3
      resourceServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000  # 10 seconds
        permittedNumberOfCallsInHalfOpenState: 3

# Logging configuration
logging:
  level:
    root: INFO
    com.nazndev.apigwservice: DEBUG  # Detailed logs for your API Gateway
    org.springframework.cloud.gateway: DEBUG  # Detailed logs for Spring Cloud Gateway
    org.springframework.boot.actuate: DEBUG

# Management and monitoring endpoints for the API Gateway
management:
  endpoint:
    health:
      show-details: always  # Show detailed health information
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Expose necessary endpoints for health, info, and metrics
  security:
    enabled: false  # Disable security for actuator endpoints


